# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 800)
        MainWindow.setMinimumSize(QtCore.QSize(607, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(10, 10, 10);")






        self.frame_ERRO_style = ("background-color: rgb(255, 114, 116);\n"
                                 "border-radius: 10px;")

        self.frame_green_style = ("background-color: rgb(81, 226, 76);\n"
                                  "border-radius: 10px;")

        self.styleOK = ("QLineEdit { \n"
                        "    border: 2px; solid rgb(45,45,45);\n"
                        "    border-radius: 5px;\n"
                        "    padding: 15px;\n"
                        "    background-color: rgb(30,30,30);\n"
                        "    color: rgb(100, 100, 100);\n"
                        "}\n"                        "QLineEdit:hover  {\n"
                        "    border: 2px solid rgb(55,55,55)\n"
                        "}\n"
                        "\n"
                        "QLineEdit:focus {\n"
                        "    border: 2px solid rgb(255, 207, 0);\n"
                        "    color: rgb(200, 200, 200);\n"
                        "} ")

        self.styleError = ("QLineEdit { \n"
                           "    border: 2px; solid rgb(255,85,127);\n"
                           "    border-radius: 5px;\n"
                           "    padding: 15px;\n"
                           "    background-color: rgb(30,30,30);\n"
                           "    color: rgb(100, 100, 100);\n"
                           "}\n"
                           "QLineEdit:hover  {\n"
                           "    border: 2px solid rgb(55,55,55)\n"
                           "}\n"
                           "\n"
                           "QLineEdit:focus {\n"
                           "    border: 2px solid rgb(255, 207, 0);\n"
                           "    color: rgb(200, 200, 200);\n"
                           "} ")








        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(607, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 6, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_error = QtWidgets.QFrame(self.top_bar)
        self.frame_error.setMaximumSize(QtCore.QSize(450, 16777215))


        self.frame_error.setStyleSheet(self.frame_ERRO_style)


        self.frame_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_2.setContentsMargins(-1, 7, -1, 11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_error.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_2.addWidget(self.label_error)
        self.botton_erro_close = QtWidgets.QPushButton(self.frame_error)
        self.botton_erro_close.setMinimumSize(QtCore.QSize(20, 20))
        self.botton_erro_close.setMaximumSize(QtCore.QSize(20, 20))
        self.botton_erro_close.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botton_erro_close.setAutoFillBackground(False)
        self.botton_erro_close.setStyleSheet("QPushButton {\n"
"    border-radius: 3px;\n"
"    background-image: url(:/close img/cil-x.png);\n"
"    background-position: center;\n"
"    \n"
"    background-color: rgb(60,60,60);\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(255, 85, 255);\n"
"    color: rgba(200, 200, 200, 200);\n"
"}\n"
"QPushbotton:pressed {\n"
"    \n"
"    background-color: rgb(35, 35, 35);\n"
"    \n"
"    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.botton_erro_close.setText("")
        self.botton_erro_close.setIconSize(QtCore.QSize(15, 15))
        self.botton_erro_close.setObjectName("botton_erro_close")
        self.horizontalLayout_2.addWidget(self.botton_erro_close)
        self.horizontalLayout.addWidget(self.frame_error)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setEnabled(True)
        self.content.setMinimumSize(QtCore.QSize(607, 707))
        self.content.setAutoFillBackground(False)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.no = QtWidgets.QHBoxLayout(self.content)
        self.no.setContentsMargins(-1, 20, -1, 20)
        self.no.setSpacing(0)
        self.no.setObjectName("no")
        self.login_area = QtWidgets.QFrame(self.content)
        self.login_area.setMinimumSize(QtCore.QSize(450, 550))
        self.login_area.setMaximumSize(QtCore.QSize(450, 550))
        self.login_area.setStyleSheet("\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"border-radius: 7px;")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.Logo = QtWidgets.QFrame(self.login_area)
        self.Logo.setGeometry(QtCore.QRect(30, -60, 391, 241))
        self.Logo.setStyleSheet("background-image: url(:/Logo/logo_360x90.png);")
        self.Logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Logo.setObjectName("Logo")
        self.avatar = QtWidgets.QFrame(self.login_area)
        self.avatar.setGeometry(QtCore.QRect(170, 120, 121, 121))
        self.avatar.setStyleSheet("QFrame {\n"
"    \n"
"    background-image: url(:/avatar/fotoperfil.jpg);\n"
"    border-radius: 60px;\n"
"    border: 8px solid rgb(255, 207, 0)\n"
"}\n"
"QFrame:hover {\n"
"    border: 8px solid rgb(255, 225, 0)\n"
"}")
        self.avatar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.avatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avatar.setObjectName("avatar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.avatar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.input_user = QtWidgets.QLineEdit(self.login_area)
        self.input_user.setGeometry(QtCore.QRect(90, 270, 280, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.input_user.setFont(font)
        self.input_user.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.input_user.setStyleSheet("QLineEdit { \n"
"    border: 2px; solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover  {\n"
"    border: 2px solid rgb(55,55,55)\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"} ")
        self.input_user.setMaxLength(32)
        self.input_user.setObjectName("input_user")
        self.input_password = QtWidgets.QLineEdit(self.login_area)
        self.input_password.setGeometry(QtCore.QRect(90, 332, 280, 55))
        self.input_password.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.input_password.setStyleSheet("QLineEdit { \n"
"    border: 2px; solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover  {\n"
"    border: 2px solid rgb(55,55,55)\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"} ")
        self.input_password.setMaxLength(16)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.check_user = QtWidgets.QCheckBox(self.login_area)
        self.check_user.setGeometry(QtCore.QRect(92, 400, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.check_user.setFont(font)
        self.check_user.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 205, 0);\n"
"    background-color: rgb(255,223,85);\n"
"    \n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 205, 0);\n"
"    background-color: rgb(255,223,85);\n"
"}\n"
"")
        self.check_user.setObjectName("check_user")
        self.conect_button = QtWidgets.QPushButton(self.login_area)
        self.conect_button.setGeometry(QtCore.QRect(90, 430, 280, 50))
        self.conect_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35,35,35);\n"
"}")
        self.conect_button.setObjectName("conect_button")
        self.no.addWidget(self.login_area)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(15,15,15);")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.bottom)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(75, 75, 75);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_error.setText(_translate("MainWindow", "Error"))
        self.input_user.setPlaceholderText(_translate("MainWindow", "USER"))
        self.input_password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.check_user.setText(_translate("MainWindow", "SAVE USER"))
        self.conect_button.setText(_translate("MainWindow", "CONNECT TO CYBERPUNK"))
        self.label.setText(_translate("MainWindow", "Created by: Vynicius Martorano"))
import dados.files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
